spring:
  application:
    name: metricix

  data:
    redis:
      host: localhost
      port: 6379
    lettuce:
      pool:
        enabled: true
        max-active: 100

  r2dbc:
    url: r2dbc:postgresql://localhost:5433/metricix_db
    username: metricix_admin
    password: super_secret_password_123

  flyway:
    url: jdbc:postgresql://localhost:5433/metricix_db
    user: metricix_admin
    password: super_secret_password_123
    enabled: true

logging:
    level:
        root: INFO
        org.springframework.web: DEBUG
        com.metricix: DEBUG